test_suite(
    name = "all_tests",
    tests = [
        "//test/conjure:validate_conjure_test",
        "//test/conjure_rust:validate_conjure_rust_test",
        "//test/conjure_typescript:validate_conjure_typescript_test",
    ],
)
